// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwsihk1ARJN6w-ZokeKKgsAchKIpM82d4',
    appId: '1:776422398981:web:3961ddf0777e8d5e82106c',
    messagingSenderId: '776422398981',
    projectId: 'mad4-e3503',
    authDomain: 'mad4-e3503.firebaseapp.com',
    storageBucket: 'mad4-e3503.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDocAHIDIcHlombaXSx0p4XYmSh3z2vgbE',
    appId: '1:776422398981:android:84eafd149b831b6f82106c',
    messagingSenderId: '776422398981',
    projectId: 'mad4-e3503',
    storageBucket: 'mad4-e3503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBXgtZGhYR7TMYCxI_00MChzWe8E4yiQ8',
    appId: '1:776422398981:ios:004be674a3f964e982106c',
    messagingSenderId: '776422398981',
    projectId: 'mad4-e3503',
    storageBucket: 'mad4-e3503.firebasestorage.app',
    iosBundleId: 'com.example.mad4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBXgtZGhYR7TMYCxI_00MChzWe8E4yiQ8',
    appId: '1:776422398981:ios:004be674a3f964e982106c',
    messagingSenderId: '776422398981',
    projectId: 'mad4-e3503',
    storageBucket: 'mad4-e3503.firebasestorage.app',
    iosBundleId: 'com.example.mad4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwsihk1ARJN6w-ZokeKKgsAchKIpM82d4',
    appId: '1:776422398981:web:a16573d52e2c491e82106c',
    messagingSenderId: '776422398981',
    projectId: 'mad4-e3503',
    authDomain: 'mad4-e3503.firebaseapp.com',
    storageBucket: 'mad4-e3503.firebasestorage.app',
  );
}
